name: RedactorPlugins
version: 1.0.1
description: Add Redactor plugins to v2
url: https://github.com/lesaff/statamicv2-redactorplugins
developer: Rudy Affandi
developer_url: https://github.com/lesaff
